version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - birbnb

  backend:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017
      - MONGODB_DB_NAME=birbnb
    working_dir: /app
    command: npm start
    networks:
      - birbnb

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=https://api.auth.localhost
    working_dir: /app
    command: npm start
    networks:
      - birbnb

  caddy:
    image: caddy:2
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend
    networks:
      - birbnb

volumes:
  mongo-data:
  caddy_data:
  caddy_config:

networks:
  birbnb:
    driver: bridge